### ISSUE TITLE
a Problem with RailName

### ISSUE THREAD

**Issue by lazytspo** [Hongmen-Technology-Industries/AdvancedRails#33]
dear creator of this ModelPack, i just wanted to tell you that your modelpack has a problem related to the RailName. it happened to all the modelpack railmodels. both 1067mm and 1435mm railmodels. here is the predicted fix: <a href="https://ibb.co/1Mqky2x"><img src="https://i.ibb.co/2StTVKB/2021-10-25-23-31-46.png" alt="2021-10-25-23-31-46" border="0"></a>
it needs to be removed. so, we'll wait.

**Comment by Kai-Z-JP** [comment]
This is not a bug, but a specification.
To adjust the position of the button in the GUI when selecting a model, we have set a little strange name for them.
Thanks for your report.

**Comment by LazytownSpo666** [comment]
> This is not a bug, but a specification. To adjust the position of the button in the GUI when selecting a model, we have set a little strange name for them. Thanks for your report.

well thanks but i'll get it fixed asap /j*

* EDIT: Just kidding, this is highly normal No fixes are required.
